DROP TABLE IF EXISTS PUBLIC."user" cascade;
DROP TABLE IF EXISTS PUBLIC."film" cascade;
DROP TABLE IF EXISTS PUBLIC."friend";
DROP TABLE IF EXISTS PUBLIC."film_genre";
DROP TABLE IF EXISTS PUBLIC."film_like";
DROP TABLE IF EXISTS PUBLIC."mpa";
DROP TABLE IF EXISTS PUBLIC."genre";

CREATE TABLE IF NOT EXISTS PUBLIC."user" (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email CHARACTER VARYING(64) NOT NULL,
	login CHARACTER VARYING(64) NOT NULL,
	name CHARACTER VARYING(64),
	birthday DATE  NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC."mpa" (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name CHARACTER VARYING(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC."film" (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name CHARACTER VARYING(128) NOT NULL,
	description CHARACTER VARYING(200) NOT NULL,
	release_date DATE  NOT NULL,
	duration INTEGER NOT NULL,
	mpa_id INTEGER NOT NULL,
    CONSTRAINT mpa_id_fk FOREIGN KEY (mpa_id) REFERENCES PUBLIC."mpa"(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC."friend" (
	user_id_1 INTEGER NOT NULL,
	user_id_2 INTEGER NOT NULL,
    CONSTRAINT friend_id_1_fk FOREIGN KEY (user_id_1) REFERENCES PUBLIC."user"(id),
    CONSTRAINT friend_id_2_fk FOREIGN KEY (user_id_2) REFERENCES PUBLIC."user"(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC."genre" (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name CHARACTER VARYING(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC."film_genre" (
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT film_id_fk FOREIGN KEY (film_id) REFERENCES PUBLIC."film"(id),
    CONSTRAINT genre_id_fk FOREIGN KEY (genre_id) REFERENCES PUBLIC."genre"(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC."film_like" (
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT film_like_id_fk FOREIGN KEY (film_id) REFERENCES PUBLIC."film"(id),
    CONSTRAINT user_like_id_fk FOREIGN KEY (user_id) REFERENCES PUBLIC."user"(id)
);